### ISSUE TITLE
我的项目能加入到列表中吗？

### ISSUE THREAD

**Issue by Piasy** [CameloeAnthony/AndroidArchitectureCollection#1]
地址：https://github.com/Piasy/AndroidTDDBootStrap

**Comment by CameloeAnthony** [comment]
可以的 。




------------------ 原始邮件 ------------------
发件人: "Piasy";<notifications@github.com>;
发送时间: 2016年4月27日(星期三) 上午7:56
收件人: "CameloeAnthony/AndroidArchitectureCollection"<AndroidArchitectureCollection@noreply.github.com>; 

主题: [CameloeAnthony/AndroidArchitectureCollection] 我的项目能加入到列表中吗？ (#1)




地址：https://github.com/Piasy/AndroidTDDBootStrap

**Comment by Piasy** [comment]
好的
